# Databricks notebook source
# MAGIC %md
# MAGIC # 004 — Gold: modelo dimensional (Kimball)

# COMMAND ----------

df_apolice = spark.read.format("delta").table("silver.apolice")
df_carro = spark.read.format("delta").table("silver.carro")
df_cliente = spark.read.format("delta").table("silver.cliente")
df_endereco = spark.read.format("delta").table("silver.endereco")
df_estado = spark.read.format("delta").table("silver.estado")
df_marca = spark.read.format("delta").table("silver.marca")
df_modelo = spark.read.format("delta").table("silver.modelo")
df_municipio = spark.read.format("delta").table("silver.municipio")
df_regiao = spark.read.format("delta").table("silver.regiao")
df_sinistro = spark.read.format("delta").table("silver.sinistro")
df_telefone = spark.read.format("delta").table("silver.telefone")

# COMMAND ----------

for name, df in [
    ("apolice", df_apolice),
    ("sinistro", df_sinistro),
    ("carro", df_carro),
    ("modelo", df_modelo),
    ("marca", df_marca),
    ("cliente", df_cliente),
    ("municipio", df_municipio),
    ("estado", df_estado),
    ("regiao", df_regiao),
]:
    df.createOrReplaceTempView(name)

# COMMAND ----------

# MAGIC %sql
# MAGIC DROP TABLE IF EXISTS gold.fato_sinistro;
# MAGIC DROP TABLE IF EXISTS gold.dim_carro;
# MAGIC DROP TABLE IF EXISTS gold.dim_cliente;
# MAGIC DROP TABLE IF EXISTS gold.dim_localidade;
# MAGIC DROP TABLE IF EXISTS gold.dim_tempo;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_carro (
# MAGIC   SK_CARRO BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   PLACA VARCHAR(10),
# MAGIC   MARCA VARCHAR(100),
# MAGIC   MODELO VARCHAR(100),
# MAGIC   COR VARCHAR(10),
# MAGIC   ANO INT,
# MAGIC   CHASSI VARCHAR(20)
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_cliente (
# MAGIC   SK_CLIENTE BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   CODIGO_CLIENTE INT,
# MAGIC   NOME VARCHAR(50),
# MAGIC   CPF VARCHAR(11),
# MAGIC   SEXO CHAR(1),
# MAGIC   DATA_NASCIMENTO DATE
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.dim_localidade (
# MAGIC   SK_LOCALIDADE BIGINT GENERATED BY DEFAULT AS IDENTITY,
# MAGIC   CODIGO_MUNICIPIO INT,
# MAGIC   NOME_MUNICIPIO VARCHAR(100),
# MAGIC   NOME_ESTADO VARCHAR(100),
# MAGIC   NOME_REGIAO VARCHAR(100)
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE gold.fato_sinistro (
# MAGIC   FK_TEMPO DATE,
# MAGIC   FK_LOCALIDADE INT,
# MAGIC   FK_CARRO INT,
# MAGIC   FK_CLIENTE INT,
# MAGIC   QTDE_SINISTRO INT
# MAGIC ) USING DELTA;

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH carros_relacional AS (
# MAGIC   SELECT c.placa, ma.nome_marca, mo.nome_modelo, c.cor, c.ano, c.chassi
# MAGIC   FROM carro c
# MAGIC   INNER JOIN modelo mo ON c.codigo_modelo = mo.codigo_modelo
# MAGIC   INNER JOIN marca ma ON mo.codigo_marca = ma.codigo_marca
# MAGIC )
# MAGIC MERGE INTO gold.dim_carro AS c
# MAGIC USING carros_relacional AS cc
# MAGIC ON c.placa = cc.placa
# MAGIC WHEN MATCHED AND (
# MAGIC   c.marca <> cc.nome_marca OR c.modelo <> cc.nome_modelo OR c.cor <> cc.cor
# MAGIC   OR c.ano <> cc.ano OR c.chassi <> cc.chassi
# MAGIC ) THEN UPDATE SET
# MAGIC   placa = cc.placa, marca = cc.nome_marca, modelo = cc.nome_modelo,
# MAGIC   cor = cc.cor, ano = cc.ano, chassi = cc.chassi
# MAGIC WHEN NOT MATCHED THEN INSERT (placa, marca, modelo, cor, ano, chassi)
# MAGIC VALUES (cc.placa, cc.nome_marca, cc.nome_modelo, cc.cor, cc.ano, cc.chassi);

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH localidade_relacional AS (
# MAGIC   SELECT m.codigo_municipio, m.nome_municipio, e.nome_estado, r.nome_regiao
# MAGIC   FROM municipio m
# MAGIC   INNER JOIN estado e ON m.codigo_estado = e.codigo_estado
# MAGIC   INNER JOIN regiao r ON e.codigo_regiao = r.codigo_regiao
# MAGIC )
# MAGIC MERGE INTO gold.dim_localidade AS d
# MAGIC USING localidade_relacional AS r
# MAGIC ON r.codigo_municipio = d.codigo_municipio
# MAGIC WHEN MATCHED AND (
# MAGIC   d.nome_municipio <> r.nome_municipio OR d.nome_estado <> r.nome_estado
# MAGIC   OR d.nome_regiao <> r.nome_regiao
# MAGIC ) THEN UPDATE SET
# MAGIC   nome_municipio = r.nome_municipio,
# MAGIC   nome_estado = r.nome_estado,
# MAGIC   nome_regiao = r.nome_regiao
# MAGIC WHEN NOT MATCHED THEN INSERT (codigo_municipio, nome_municipio, nome_estado, nome_regiao)
# MAGIC VALUES (r.codigo_municipio, r.nome_municipio, r.nome_estado, r.nome_regiao);

# COMMAND ----------

# COMMAND ----------

# Ajuste de tipos antes do MERGE (evita CPF em notação científica)
from pyspark.sql import functions as F

df_cliente = (
    spark.table("silver.cliente")
    .select(
        F.col("CODIGO_CLIENTE").cast("int").alias("codigo_cliente"),
        F.col("NOME").alias("nome"),
        F.lpad(F.col("CPF").cast("double").cast("long").cast("string"), 11, "0").alias("cpf"),
        F.col("SEXO").alias("sexo"),
        F.col("DATA_NASCIMENTO").cast("date").alias("data_nascimento"),
    )
)
df_cliente.createOrReplaceTempView("cliente")

# COMMAND ----------

# MAGIC %sql
# MAGIC WITH cliente_relacional AS (
# MAGIC   SELECT codigo_cliente, nome, cpf, sexo, data_nascimento FROM cliente
# MAGIC )
# MAGIC MERGE INTO gold.dim_cliente AS d
# MAGIC USING cliente_relacional AS r
# MAGIC ON r.codigo_cliente = d.codigo_cliente
# MAGIC WHEN MATCHED AND (
# MAGIC   d.nome <> r.nome OR d.cpf <> r.cpf OR d.sexo <> r.sexo
# MAGIC   OR d.data_nascimento <> r.data_nascimento
# MAGIC ) THEN UPDATE SET
# MAGIC   nome = r.nome, cpf = r.cpf, sexo = r.sexo, data_nascimento = r.data_nascimento
# MAGIC WHEN NOT MATCHED THEN INSERT (codigo_cliente, nome, cpf, sexo, data_nascimento)
# MAGIC VALUES (r.codigo_cliente, r.nome, r.cpf, r.sexo, r.data_nascimento);

# COMMAND ----------

data_inicial = "2023-01-01"
data_final = "2026-12-31"
num_dias = spark.sql(f"SELECT datediff('{data_final}', '{data_inicial}')").collect()[0][0]

df_calendario = spark.range(0, num_dias + 1).selectExpr(
    f"date_add(to_date('{data_inicial}'), CAST(id AS INT)) AS Data"
)

df_tempo = df_calendario.selectExpr(
    "Data",
    "year(Data) AS Ano",
    "month(Data) AS Mes",
    """(CASE month(Data)
        WHEN 1 THEN 'JANEIRO' WHEN 2 THEN 'FEVEREIRO' WHEN 3 THEN 'MARCO'
        WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAIO' WHEN 6 THEN 'JUNHO'
        WHEN 7 THEN 'JULHO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETEMBRO'
        WHEN 10 THEN 'OUTUBRO' WHEN 11 THEN 'NOVEMBRO' WHEN 12 THEN 'DEZEMBRO'
    END) AS NomeMes""",
    "day(Data) AS Dia",
    """(CASE dayofweek(Data)
        WHEN 1 THEN 'DOMINGO' WHEN 2 THEN 'SEGUNDA-FEIRA' WHEN 3 THEN 'TERCA-FEIRA'
        WHEN 4 THEN 'QUARTA-FEIRA' WHEN 5 THEN 'QUINTA-FEIRA' WHEN 6 THEN 'SEXTA-FEIRA'
        WHEN 7 THEN 'SABADO'
    END) AS NomeDiaSemana""",
    "dayofweek(Data) AS NumeroDiaSemana",
)

df_tempo.write.format("delta").mode("overwrite").saveAsTable("gold.dim_tempo")

# COMMAND ----------

# MAGIC %sql
# MAGIC INSERT INTO gold.fato_sinistro
# MAGIC WITH apolice_cliente AS (
# MAGIC   SELECT a.codigo_cliente, a.placa
# MAGIC   FROM apolice a
# MAGIC   INNER JOIN cliente c ON a.codigo_cliente = c.codigo_cliente
# MAGIC )
# MAGIC SELECT
# MAGIC   CAST(r.data_sinistro AS DATE) AS fk_tempo,
# MAGIC   dloc.sk_localidade AS fk_localidade,
# MAGIC   dcar.sk_carro AS fk_carro,
# MAGIC   dcli.sk_cliente AS fk_cliente,
# MAGIC   COUNT(1) AS qtde_sinistro
# MAGIC FROM sinistro r
# MAGIC INNER JOIN gold.dim_carro dcar ON TRIM(r.placa) = TRIM(dcar.placa)
# MAGIC INNER JOIN apolice_cliente ac ON TRIM(ac.placa) = TRIM(r.placa)
# MAGIC INNER JOIN gold.dim_cliente dcli ON ac.codigo_cliente = dcli.codigo_cliente
# MAGIC INNER JOIN gold.dim_localidade dloc ON r.local_sinistro = dloc.codigo_municipio
# MAGIC INNER JOIN gold.dim_tempo dtem ON CAST(r.data_sinistro AS DATE) = dtem.data
# MAGIC GROUP BY 1, 2, 3, 4;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT 'dim_carro' AS tabela, COUNT(*) AS linhas FROM gold.dim_carro
# MAGIC UNION ALL SELECT 'dim_cliente', COUNT(*) FROM gold.dim_cliente
# MAGIC UNION ALL SELECT 'dim_localidade', COUNT(*) FROM gold.dim_localidade
# MAGIC UNION ALL SELECT 'dim_tempo', COUNT(*) FROM gold.dim_tempo
# MAGIC UNION ALL SELECT 'fato_sinistro', COUNT(*) FROM gold.fato_sinistro
